---
# tasks file for ansible-role-rpmfusion
- name: Install RPMfusion repositories
  become: yes
  command: dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
  args:
    creates: /etc/yum.repos.d/rpmfusion-free.repo
    removes: /etc/fedora-release

- name: Install AppStream metadata
  become: yes
  command: dnf groupupdate core -y

- name: Install tainted repositories
  become: yes
  package:
    name:
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted
    state: present
